sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t notsimpletext/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true notsimpletext/react-test npm test

after_success:
  - docker build -t notsimpletext/multi-client ./client
  - docker build -t notsimpletext/multi-nginx ./nginx
  - docker build -t notsimpletext/multi-server ./server
  - docker build -t notsimpletext/multi-worker ./worker
# log in to tje docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# tagging
#  - docker tag dimamikhalchuk/multi-client:latest
 # - docker tag dimamikhalchuk/multi-nginx:latest
 # - docker tag dimamikhalchuk/multi-server:latest
#  - docker tag dimamikhalchuk/multi-worker:latest
# take those images and push them to docker hub
  - docker push notsimpletext/multi-client
  - docker push notsimpletext/multi-nginx
  - docker push notsimpletext/multi-server
  - docker push notsimpletext/multi-worker