sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t notsimpletext/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true notsimpletext/react-test npm test

after_success:
  - docker build -t notsimpletext/multi-client ./client
  - docker build -t notsimpletext/multi-nginx ./nginx
  - docker build -t notsimpletext/multi-server ./server
  - docker build -t notsimpletext/multi-worker ./worker
# log in to tje docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# tagging
  - docker tag multi-client dimamikhalchuk/multi-client
  - docker tag multi-nginx dimamikhalchuk/multi-nginx
  - docker tag multi-server dimamikhalchuk/multi-server
  - docker tag multi-worker dimamikhalchuk/multi-worker
# take those images and push them to docker hub
  - docker push dimamikhalchuk/multi-client
  - docker push dimamikhalchuk/multi-nginx
  - docker push dimamikhalchuk/multi-server
  - docker push dimamikhalchuk/multi-worker